### ISSUE TITLE
Yaml Mapping

### ISSUE THREAD

**Issue by ghanbari** [Prezent/doctrine-translatable#22]
i have a symfony project & I use yaml format in my bundle, but it not create properties for my entity.
do it need specify configuration?
my entity mapping:
```yaml
Anar\EngineBundle\Entity\Blog:
    type: entity
    table: blog
    repositoryClass: Anar\EngineBundle\Entity\BlogRepository
    prezent:
        translatable:
            field: translations
            targetEntity: BlogTranslation
            currentLocale: currentLocale
            fallbackLocale: fallbackLocale
    gedmo:
        tree:
            type: nested
    id:
        id:
            type: integer
            id: true
            generator:
                strategy: AUTO
    fields:
        name:
            unique: true
            length: 50
        theme:
            length: 100
            options:
                default: Public
        onTree:
            type: boolean
            options:
                default: true
        active:
            type: boolean
            options:
                default: true
        lft:
            type: integer
            gedmo:
                - treeLeft
        rgt:
            type: integer
            gedmo:
                - treeRight
        root:
            type: integer
            nullable: true
            gedmo:
                - treeRoot
        lvl:
            type: integer
            gedmo:
                - treeLevel
        createdAt:
            type: datetime
            gedmo:
                timestampable:
                    on: create
        updatedAt:
            type: datetime
            gedmo:
                timestampable:
                    on: update
    manyToOne:
        parent:
            targetEntity: Blog
            inversedBy: children
            joinColumn:
                name: parent_id
                referencedColumnName: id
                onDelete: restrict
            gedmo:
                - treeParent
    oneToMany:
        children:
            targetEntity: Blog
            mappedBy: parent
            orderBy:
                lft: ASC
    manyToMany:
        apps:
            targetEntity: App
            inversedBy: blogs
            joinTable:
                name: blogs_apps
                joinColumns:
                    blog_id:
                        referencedColumnName: id
                inverseJoinColumns:
                    app_id:
                        referencedColumnName: id

```
